services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      JWT_SECRET: $JWT_SECRET
      JWT_TIME: $JWT_TIME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock